# Analyse exploratoire

Notre objectif est d'analysé les données du pilote leclerc pendant la course de Monza en 2022.

In [1]:
pip install fastf1

Collecting fastf1
  Downloading fastf1-3.8.3-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: cryptography in /usr/local/lib/python3.12/dist-packages (from fastf1) (43.0.3)
Requirement already satisfied: matplotlib<4.0.0,>=3.8.0 in /usr/local/lib/python3.12/dist-packages (from fastf1) (3.10.0)
Requirement already satisfied: numpy<3.0.0,>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from fastf1) (2.0.2)
Requirement already satisfied: pandas<3.0.0,>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from fastf1) (2.2.2)
Requirement already satisfied: platformdirs in /usr/local/lib/python3.12/dist-packages (from fastf1) (4.9.6)
Requirement already satisfied: pydantic in /usr/local/lib/python3.12/dist-packages (from fastf1) (2.12.3)
Requirement already satisfied: pyjwt in /usr/local/lib/python3.12/dist-packages (from fastf1) (2.12.1)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.12/dist-packages (from fastf1) (2.9.0.post0)
Collecting rapidfuzz (from fastf1)
  Downloading rapidfuzz-3.14.5-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (12 kB)
Collecting requests-cache>=1.0.0 (from fastf1)
  Downloading requests_cache-1.3.2-py3-none-any.whl.metadata (9.4 kB)
Requirement already satisfied: requests>=2.30.0 in /usr/local/lib/python3.12/dist-packages (from fastf1) (2.32.4)
Requirement already satisfied: scipy<2.0.0,>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from fastf1) (1.16.3)
Collecting signalrcore (from fastf1)
  Downloading signalrcore-1.0.2-py3-none-any.whl.metadata (13 kB)
Collecting timple>=0.1.6 (from fastf1)
  Downloading timple-0.1.8-py3-none-any.whl.metadata (2.0 kB)
Requirement already satisfied: websockets>=10.3 in /usr/local/lib/python3.12/dist-packages (from fastf1) (15.0.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4.0.0,>=3.8.0->fastf1) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4.0.0,>=3.8.0->fastf1) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4.0.0,>=3.8.0->fastf1) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4.0.0,>=3.8.0->fastf1) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4.0.0,>=3.8.0->fastf1) (26.1)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4.0.0,>=3.8.0->fastf1) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4.0.0,>=3.8.0->fastf1) (3.3.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0.0,>=2.1.1->fastf1) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0.0,>=2.1.1->fastf1) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil->fastf1) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.30.0->fastf1) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.30.0->fastf1) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.30.0->fastf1) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.30.0->fastf1) (2026.4.22)
Requirement already satisfied: attrs>=21.2 in /usr/local/lib/python3.12/dist-packages (from requests-cache>=1.0.0->fastf1) (26.1.0)
Collecting cattrs>=22.2 (from requests-cache>=1.0.0->fastf1)
  Downloading cattrs-26.1.0-py3-none-any.whl.metadata (8.5 kB)
Collecting url-normalize>=2.0 (from requests-cache>=1.0.0->fastf1)
  Downloading url_normalize-3.0.0-py3-none-any.whl.metadata (7.5 kB)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.12/dist-packages (from cryptography->fastf1) (2.0.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic->fastf1) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic->fastf1) (2.41.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.12/dist-packages (from pydantic->fastf1) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic->fastf1) (0.4.2)
Requirement already satisfied: msgpack==1.1.2 in /usr/local/lib/python3.12/dist-packages (from signalrcore->fastf1) (1.1.2)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.12->cryptography->fastf1) (3.0)
Downloading fastf1-3.8.3-py3-none-any.whl (135 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 136.0/136.0 kB 4.6 MB/s eta 0:00:00
Downloading requests_cache-1.3.2-py3-none-any.whl (70 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.6/70.6 kB 3.3 MB/s eta 0:00:00
Downloading timple-0.1.8-py3-none-any.whl (17 kB)
Downloading rapidfuzz-3.14.5-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (3.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 53.7 MB/s eta 0:00:00
Downloading signalrcore-1.0.2-py3-none-any.whl (55 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.6/55.6 kB 3.4 MB/s eta 0:00:00
Downloading cattrs-26.1.0-py3-none-any.whl (73 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.1/73.1 kB 5.0 MB/s eta 0:00:00
Downloading url_normalize-3.0.0-py3-none-any.whl (16 kB)
Installing collected packages: url-normalize, signalrcore, rapidfuzz, cattrs, requests-cache, timple, fastf1
Successfully installed cattrs-26.1.0 fastf1-3.8.3 rapidfuzz-3.14.5 requests-cache-1.3.2 signalrcore-1.0.2 timple-0.1.8 url-normalize-3.0.0

In [2]:
# Chargement de la bibliothèque fastf1 ainsi que le cache
import fastf1
from pathlib import Path

CACHE_DIR = Path("/content/fastf1_cache")
CACHE_DIR.mkdir(parents=True, exist_ok=True)

fastf1.Cache.enable_cache(str(CACHE_DIR))

In [3]:
import logging
import warnings

warnings.filterwarnings("ignore")

for logger_name in [
    "fastf1",
    "fastf1.fastf1",
    "fastf1.fastf1.req",
    "fastf1.api"
]:
    logging.getLogger(logger_name).setLevel(logging.ERROR)

# Structure des données

Dans cette étape nous allons sélectionner les données en rapport avec la pilote puis faire un étude afin de comprendre la structure des données

In [4]:
# Chargement de la course de Monza en 2022
session = fastf1.get_session(2022, 'Monza', 'R')
session.load()
laps = session.laps

In [5]:
laps_lec = laps.pick_driver('LEC')
laps_lec.info()

<class 'fastf1.core.Laps'>
Index: 53 entries, 190 to 242
Data columns (total 31 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Time                53 non-null     timedelta64[ns]
 1   Driver              53 non-null     object
 2   DriverNumber        53 non-null     object
 3   LapTime             53 non-null     timedelta64[ns]
 4   LapNumber           53 non-null     float64
 5   Stint               53 non-null     float64
 6   PitOutTime          3 non-null      timedelta64[ns]
 7   PitInTime           3 non-null      timedelta64[ns]
 8   Sector1Time         52 non-null     timedelta64[ns]
 9   Sector2Time         53 non-null     timedelta64[ns]
 10  Sector3Time         53 non-null     timedelta64[ns]
 11  Sector1SessionTime  52 non-null     timedelta64[ns]
 12  Sector2SessionTime  53 non-null     timedelta64[ns]
 13  Sector3SessionTime  53 non-null     timedelta64[ns]
 14  SpeedI1             53 non-null     float64
 15  SpeedI2             53 non-null     float64
 16  SpeedFL             50 non-null     float64
 17  SpeedST             53 non-null     float64
 18  IsPersonalBest      53 non-null     object
 19  Compound            53 non-null     object
 20  TyreLife            53 non-null     float64
 21  FreshTyre           53 non-null     bool
 22  Team                53 non-null     object
 23  LapStartTime        53 non-null     timedelta64[ns]
 24  LapStartDate        53 non-null     datetime64[ns]
 25  TrackStatus         53 non-null     object
 26  Position            53 non-null     float64
 27  Deleted             53 non-null     bool
 28  DeletedReason       53 non-null     object
 29  FastF1Generated     53 non-null     bool
 30  IsAccurate          53 non-null     bool
dtypes: bool(4), datetime64[ns](1), float64(8), object(7), timedelta64[ns](11)
memory usage: 11.8+ KB

La table contenant les information du pilote Leclerc contient 31 colonnes avec des types tels que :
bool, datetime64[ns], float64, object, timedelta64[ns]

In [6]:
laps_lec.head()

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate
190,0 days 01:03:56.469000,LEC,16,0 days 00:01:28.085000,1.0,1.0,NaT,NaT,NaT,0 days 00:00:29.537000,...,True,Ferrari,0 days 01:02:28.137000,2022-09-11 13:03:28.378,1,1.0,False,,False,False
191,0 days 01:05:23.004000,LEC,16,0 days 00:01:26.535000,2.0,1.0,NaT,NaT,0 days 00:00:28.687000,0 days 00:00:29.260000,...,True,Ferrari,0 days 01:03:56.469000,2022-09-11 13:04:56.710,1,1.0,False,,False,True
192,0 days 01:06:49.356000,LEC,16,0 days 00:01:26.352000,3.0,1.0,NaT,NaT,0 days 00:00:28.359000,0 days 00:00:29.434000,...,True,Ferrari,0 days 01:05:23.004000,2022-09-11 13:06:23.245,1,1.0,False,,False,True
193,0 days 01:08:15.158000,LEC,16,0 days 00:01:25.802000,4.0,1.0,NaT,NaT,0 days 00:00:28.202000,0 days 00:00:29.144000,...,True,Ferrari,0 days 01:06:49.356000,2022-09-11 13:07:49.597,1,1.0,False,,False,True
194,0 days 01:09:41.060000,LEC,16,0 days 00:01:25.902000,5.0,1.0,NaT,NaT,0 days 00:00:28.140000,0 days 00:00:29.351000,...,True,Ferrari,0 days 01:08:15.158000,2022-09-11 13:09:15.399,1,1.0,False,,False,True

In [7]:
laps_lec.columns

Index(['Time', 'Driver', 'DriverNumber', 'LapTime', 'LapNumber', 'Stint',
       'PitOutTime', 'PitInTime', 'Sector1Time', 'Sector2Time', 'Sector3Time',
       'Sector1SessionTime', 'Sector2SessionTime', 'Sector3SessionTime',
       'SpeedI1', 'SpeedI2', 'SpeedFL', 'SpeedST', 'IsPersonalBest',
       'Compound', 'TyreLife', 'FreshTyre', 'Team', 'LapStartTime',
       'LapStartDate', 'TrackStatus', 'Position', 'Deleted', 'DeletedReason',
       'FastF1Generated', 'IsAccurate'],
      dtype='object')

In [8]:
laps_lec.shape

(53, 31)

Il y 53 lignes et 31 colennes dans ce dataset en d'autre terme nous avons 53 tours dans cette courses et 31 informations par tour

In [9]:
laps_lec.isna().sum()

Time                   0
Driver                 0
DriverNumber           0
LapTime                0
LapNumber              0
Stint                  0
PitOutTime            50
PitInTime             50
Sector1Time            1
Sector2Time            0
Sector3Time            0
Sector1SessionTime     1
Sector2SessionTime     0
Sector3SessionTime     0
SpeedI1                0
SpeedI2                0
SpeedFL                3
SpeedST                0
IsPersonalBest         0
Compound               0
TyreLife               0
FreshTyre              0
Team                   0
LapStartTime           0
LapStartDate           0
TrackStatus            0
Position               0
Deleted                0
DeletedReason          0
FastF1Generated        0
IsAccurate             0
dtype: int64

Les colonnes Sector1SectionTime1 , SpeedFL, Sector1Time, PitinTime, PitOutTime possède des varaiable null

In [22]:
laps_lec_reduced = laps_lec[[
    "LapNumber",
    "LapTime",
    "Sector1Time",
    "Sector2Time",
    "Sector3Time",
    "Compound",
    "TyreLife",
    "Stint",
    "PitInTime",
    "PitOutTime",
    "IsAccurate"
]]
laps_lec_reduced.head()

,LapNumber,LapTime,Sector1Time,Sector2Time,Sector3Time,Compound,TyreLife,Stint,PitInTime,PitOutTime,IsAccurate
190,1.0,0 days 00:01:28.085000,NaT,0 days 00:00:29.537000,0 days 00:00:28.715000,SOFT,1.0,1.0,NaT,NaT,False
191,2.0,0 days 00:01:26.535000,0 days 00:00:28.687000,0 days 00:00:29.260000,0 days 00:00:28.588000,SOFT,2.0,1.0,NaT,NaT,True
192,3.0,0 days 00:01:26.352000,0 days 00:00:28.359000,0 days 00:00:29.434000,0 days 00:00:28.559000,SOFT,3.0,1.0,NaT,NaT,True
193,4.0,0 days 00:01:25.802000,0 days 00:00:28.202000,0 days 00:00:29.144000,0 days 00:00:28.456000,SOFT,4.0,1.0,NaT,NaT,True
194,5.0,0 days 00:01:25.902000,0 days 00:00:28.140000,0 days 00:00:29.351000,0 days 00:00:28.411000,SOFT,5.0,1.0,NaT,NaT,True